server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled=true:
      routes:
        - id: after_route
          uri: lb://cloud-consume-order
          predicates:
            - Path=/order/**

