server:
  port: 8081

spring:
  application:
    name: cloud-provider-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8090
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: sentineltext
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.buys.springcloud.entity #所有Entity别名类所在包
